config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/show'
  get 'documents/new'

  get 'classrooms/index'
  get 'classrooms/show'
  get 'classrooms/associate'
  
  get 'users/index'
  get 'users/new'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'users#index'

  resources :users, :classrooms, :documents # or resource :user for singular resources
  resources :account_activations, only: [:edit]

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :documents
  validates :name, presence: true, length: {maximum: 20}, uniqueness: {case_sensitive: true}

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  #include Git
  before_action :logged_user
  before_action :right_user, only: [:show]

  def index
    @classrooms = Classroom.all
  end

  def show
    @classroom = Classroom.find(params[:id])
    save_classroom(@classroom)
  end

  def create
    @classroom = Classroom.new(classroom_params)
    if @classroom.save
      #create_repo(normalize(@classroom.name))
      current_user.classrooms << @classroom
      flash[:success] = 'Classroom successfully created!'
    else
      flash[:danger] = 'Classroom could not be created.'
    end
    redirect_to current_user
  end

  def associate
    @classroom = Classroom.find(params[:id])
    unless @classroom.nil? || current_user.classrooms.include?(@classroom)
      current_user.classrooms << @classroom 
      flash[:success] = 'Classroom successfully joined!'
      redirect_to @classroom
    else
      flash[:danger] = 'Already joined or unexisting classroom.'
      redirect_to classrooms_path
    end

  end

  def destroy
  end

  private
  def classroom_params
    params.require(:classroom).permit(:name)
  end

  def right_user
    @classroom = Classroom.find(params[:id])
    unless current_user.classrooms.include?(@classroom)
      flash[:danger] = "You are not member of this class."
      redirect_to current_user
    end
  end

end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_classroom.html.erb
<%= link_to classroom, title: "Enter classroom", class: "box center btn btn-lg btn-success" do %>
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span> 
  <span>
    <%= classroom.name %>	
  </span>
<% end %>

app/views/classrooms/index.html.erb
<h1> Currently available classrooms </h1>

<div class="row">
  <% @classrooms.each do |classroom| %>
    <%= link_to classrooms_associate_path(id: classroom.id), title: "Enter classroom", class: "box center btn btn-lg btn-success" do %>
      <span class="glyphicon glyphicon-book" aria-hidden="true"></span> 
      <span>
	<%= classroom.name %>	
      </span>
    <% end %>
  <% end %>
</div>

app/views/classrooms/new.html.erb
<h1>Classrooms#new</h1>
<p>Find me in app/views/classrooms/new.html.erb</p>

app/views/classrooms/show.html.erb
<h1> <%= @classroom.name %> </h1>

<%= link_to new_document_path, title: "New document", class: "btn btn-lg btn-success" do %>
  New document
<% end %>

<div class="row">
  <%= render @classroom.documents %>
</div>