config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/show'
  get 'documents/new'

  get 'classrooms/index'
  get 'classrooms/show'
  get 'classrooms/associate'
  
  get 'users/index'
  get 'users/new'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'users#index'

  resources :users, :classrooms, :documents # or resource :user for singular resources
  resources :account_activations, only: [:edit]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :activation_token
  has_and_belongs_to_many :classrooms
  before_save { self.email = email.downcase }
  before_create :create_activation_digest

  validates :name, presence: true, length: {maximum: 50}
  validates :surname, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6 }

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    return false if activation_digest.nil?
    BCrypt::Password.new(activation_digest).is_password?(token)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

   def send_activation_email
     UserMailer.account_activation(self).deliver_now
   end

  private
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_user, only: [:show]
  before_action :right_user, only: [:show]

  def index
    @user_list = User.all 
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @classroom = @user.classrooms.build
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url

      #login @user
      #flash[:success] = "Congratulations! You are now registered."
      #redirect_to @user
    else
      render new_user_path
    end
  end


   #def random_string
   #('a'..'z').to_a.shuffle[0..10].join
   #end

   private
   def user_params
     params.require(:user).permit(:name, :surname, :email, :password)
   end

   def right_user
     @user = User.find(params[:id])
     unless @user == current_user
       flash[:danger] = "You do not have permissions to access this page."
       redirect_to current_user
     end
   end

end

app/helpers/users_helper.rb
module UsersHelper

  def logged_user
    unless logged?
      save_forward_url
      flash[:danger] = "Please log in to visit this page."
      redirect_to login_path
    end
  end

end

app/views/users/index.html.erb
<%= render "shared/slider" %>
<div class="center jumbotron">

  <br>
  <br>
  <h1> Welcome to Marmoset online App </h1>
  <br>
  <br>

  <% if logged? %>
    <%= link_to "Go to your profile", current_user, class: "btn btn-lg btn-success", id: "signup" %>
  <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary", id: "signup" %>
  <% end %>

</div>

app/views/users/new.html.erb
<h1> Signup Page </h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= form_for @user, :html => {:class => "form-horizontal center"}  do |f| %>

    <%= render 'shared/error_messages' %>

    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "First name" %>
    </div>

    <div class="form-group">
      <%= f.text_field :surname, class: "form-control", placeholder: "Last name"%>
    </div>

    <div class="form-group">
      <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
    </div>

    <div class="form-group">
      <%= f.password_field :password, class: "form-control", placeholder: "Password"%>
    </div>

    <%= f.submit "Create my account", class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<h1> Welcome <%= current_user.name %>! </h1>

<%= link_to classrooms_path, title: "Join Classroom", class: "btn btn-lg btn-primary", id: "newClass" do %>
  <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
<% end %>

<%= render 'shared/drop_down_form' %>

<div class="row">
  <%= render current_user.classrooms %>
</div>