config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/show'
  get 'documents/new'

  get 'classrooms/index'
  get 'classrooms/show'
  get 'classrooms/associate'
  
  get 'users/index'
  get 'users/new'
  get 'signup' => 'users#new'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root to: 'users#index'

  resources :users, :classrooms, :documents # or resource :user for singular resources
  resources :account_activations, only: [:edit]

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :classroom
  validates :name, presence: true, length: {maximum: 20}, 
    uniqueness: {case_sensitive: true, scope: :classroom_id}
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  #include Git
  before_action :logged_user, only: [:new, :create, :destroy, :edit, :update]

  def show
    @document = Document.find(params[:id])
    #@content = read_file(@document)
  end

  def new
    @document = current_classroom.documents.build
  end

  def create
    @document = current_classroom.documents.build(document_params)
    if @document.save
      # heroku does not support local file writing
      #create_and_write_file(@document) #create and store local file
      #add_file(normalize(@document.name), normalize(@document.content))

      flash[:success] = 'Document successfully created!'
      redirect_to current_classroom
    else
      flash.now[:danger] = 'Document could not be created.'
      render 'new'
    end
  end

  def destroy
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    #old_path = path(@document)
    if @document.update_attributes(document_params)
      #update_file(old_path, @document)

      flash[:success] = 'Document successfully updated!'
      redirect_to @document.classroom
    else
      flash.now[:danger] = 'Cannot update document.'
      render 'edit'
    end
  end

  private
  def document_params
    params.require(:document).permit(:name, :content)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper

  def create_and_write_file(document)
    dir = directory(document)
    Dir.mkdir(dir) unless File.directory?(dir)
    File.write(path(document), document.content)
  end

  def update_file(old_path, new_document)
    File.delete old_path
    File.write path(new_document), new_document.content
  end

  def read_file(document)
    File.read(path(document))
  end

  private
  def normalize(file_name)
    file_name.gsub(' ', '_')
  end
  
  def path(document)
    normalize(directory(document) + document.name)
  end

  def directory(document)
    normalize("uploads/" + document.classroom.name + "/")
  end

end

app/views/documents/_document.html.erb
<%= link_to document, title: "Show document", class: "box center btn btn-lg btn-primary" do %>
  <span class="glyphicon glyphicon-file" aria-hidden="true"></span> 
  <span>
    <%= document.name %>
  </span>
<% end %>

app/views/documents/edit.html.erb
<h1> Document online editor (edit) </h1>

<%= render 'shared/editor' %>

app/views/documents/new.html.erb
<h1> Document online editor (new)</h1>

<%= render 'shared/editor' %>

app/views/documents/show.html.erb
<%= link_to edit_document_path(@document), title: "Edit", class: "btn btn-lg btn-success", id: "editButton" do %>
  Edit
<% end %>

<div class="container document">
  <h1> <%= @document.name %> </h1>
  <p>
  <%= simple_format @document.content%>
  </p>
</div>